[package]
name = "cryo"
version = "0.1.0"
edition = "2024"
authors = ["Davis Raymond Muro <git@davisraym.com>"]
license = "MIT"

[[bin]]
name = "cli"
test = true

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
thiserror = "2.0.12"

[dev-dependencies]
tempdir = "0.3.7"
